apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: fraud-shield
  labels:
    app.kubernetes.io/name: fraud-shield
    app.kubernetes.io/component: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: fraud-shield
  labels:
    app.kubernetes.io/name: fraud-shield
    app.kubernetes.io/component: database
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
        app.kubernetes.io/name: fraud-shield
        app.kubernetes.io/component: database
        tier: backend
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: fraud-shield-config
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: fraud-shield-config
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fraud-shield-secret
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - fraud_user
                - -d
                - frauddb
            initialDelaySeconds: 30
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - fraud_user
                - -d
                - frauddb
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: fraud-shield
  labels:
    app.kubernetes.io/name: fraud-shield
    app.kubernetes.io/component: database
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432

