# используем latest (оч нестабильно)
FROM python:latest

# копируем ВСЁ сразу (включая .git, IDE-файлы)
COPY . .

# зависимости без --no-cache-dir
RUN pip install -r requirements.txt

# Запускаем от root

EXPOSE 8000

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]